### ISSUE TITLE
Debug Issue where History Length is 0

### ISSUE THREAD

**Issue by mdr223** [mit-submit/A2rchi#123]
There's a recurring issue in the logs where the user causes the chain to execute with an empty history, causing the following error:
```
10.29.164.170 - - [25/Oct/2023 15:29:10] "POST /api/get_chat_response HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/A2rchi/interfaces/chat_app/app.py", line 213, in get_chat_response
    response, discussion_id = self.chat(history, discussion_id)
  File "/usr/local/lib/python3.10/site-packages/A2rchi/interfaces/chat_app/app.py", line 153, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/A2rchi/interfaces/chat_app/app.py", line 125, in __call__
    inp = history[-1][1]
IndexError: list index out of range
```
We need to perform RCA to discover what causes this issue, which can then replace our hotfix.

**Comment by julius-heitkoetter** [comment]
Just wanted to double check, this issue will be resolved with PR #130, correct?
